"""LLM analyst report from structured evidence (no images).

The fallback template and a real model report are now distinguishable: the
template is explicitly labelled and the caller receives an ``llm_called`` flag.
Previously the two were byte-indistinguishable after the fact, and nothing in
the result JSON recorded which one had been produced.
"""

from __future__ import annotations

import json
import os

import anthropic

from satchangegate.vlm.client import (
    DEFAULT_MAX_RETRIES,
    DEFAULT_TIMEOUT_S,
    UsageRecord,
    _usage_from,
    resolve_model,
)
from satchangegate.vlm.schemas import ReportInput

DEFAULT_LLM_MODEL = "claude-sonnet-5"
DEFAULT_MAX_TOKENS = 2000

REPORT_SYSTEM = """You are a geospatial analyst writing a concise change-detection report.

Use only the structured JSON evidence provided — you have not seen the images.
Write markdown with these sections:
## AOI
## Date range
## Overall verdict
## Change type
## Confidence
## Evidence from indices
## Evidence from model
## Evidence from VLM
## Artifact and weather risk
## Recommended next step

Be factual and cite numbers from the evidence. Where a quality field is null it
means that property could not be assessed for this source — say "not assessed"
rather than reporting it as zero."""


def generate_analyst_report(
    report_input: ReportInput,
    api_key: str | None = None,
    model: str | None = None,
) -> tuple[str, bool, UsageRecord | None]:
    """Return (markdown, llm_called, usage).

    Falls back to a clearly-labelled template when no API key is available.
    """
    key = api_key or os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        return _fallback_report(report_input), False, None

    model = resolve_model(model, "ANTHROPIC_LLM_MODEL", DEFAULT_LLM_MODEL)
    client = anthropic.Anthropic(
        api_key=key, timeout=DEFAULT_TIMEOUT_S, max_retries=DEFAULT_MAX_RETRIES
    )
    evidence = report_input.model_dump(mode="json")

    response = client.messages.create(
        model=model,
        max_tokens=DEFAULT_MAX_TOKENS,
        system=REPORT_SYSTEM,
        messages=[
            {
                "role": "user",
                "content": "Generate the analyst report from this evidence:\n"
                + json.dumps(evidence, indent=2),
            }
        ],
    )
    record = _usage_from(response, model, "llm")

    if getattr(response, "stop_reason", None) == "refusal":
        return _fallback_report(report_input), False, record

    text = "".join(
        getattr(block, "text", "")
        for block in response.content
        if getattr(block, "type", None) == "text"
    )
    if not text.strip():
        return _fallback_report(report_input), False, record

    header = f"<!-- generated by {model}; tokens in={record.input_tokens} out={record.output_tokens} -->\n"
    return header + text, True, record


def _fmt(value: object, suffix: str = "") -> str:
    """Render a value, distinguishing 'not assessed' from zero."""
    return "not assessed" if value is None else f"{value}{suffix}"


def _fallback_report(inp: ReportInput) -> str:
    """Deterministic template used when no API key is configured."""
    c = inp.classical
    vlm = inp.vlm
    vlm_section = "VLM not invoked (gate filtered the pair, or no API key)."
    if vlm:
        vlm_section = (
            f"VLM verdict: {vlm.vlm_verdict}, type: {vlm.change_type}, "
            f"confidence: {vlm.confidence}. Evidence: " + "; ".join(vlm.visual_evidence)
        )
    return f"""<!-- TEMPLATE REPORT: generated offline without an LLM. Not model output. -->
# Change Detection Report (template)

## AOI
{inp.aoi_id}

## Date range
{inp.date_t1} to {inp.date_t2}

## Overall verdict
Classical gate: **{c.classical_gate}** ({c.gate_reason}). Changed area: {c.changed_area_percent}%.

## Change type
{vlm.change_type if vlm else "pending / not verified"}

## Confidence
Gate confidence: {c.gate_confidence}. Observation quality: {_fmt(inp.quality.quality_score)}.

## Evidence from indices
NDVI delta mean: {c.ndvi_delta_mean:+.4f} (|mean| {c.ndvi_delta_abs_mean:.4f}); \
NDBI delta mean: {c.ndbi_delta_mean:+.4f}; NDWI delta mean: {c.ndwi_delta_mean:+.4f}.
{"Indices derive from RGB-only imagery and are not physically calibrated." if c.rgb_only else ""}

## Evidence from model
SSIM: {c.ssim}, pHash distance: {c.phash_distance}, CVA mean: {c.cva_magnitude_mean}.

## Evidence from VLM
{vlm_section}

## Artifact and weather risk
Cloud max: {_fmt(c.cloud_fraction_max)}, snow max: {_fmt(c.snow_fraction_max)}, \
registration error: {_fmt(c.registration_error_px, " px")}, \
season separation: {_fmt(c.season_delta_days, " days")}.

## Recommended next step
{"Human review recommended." if (vlm and vlm.requires_human_review) else "Monitor next acquisition or expand AOI review."}
"""
